### PR TITLE
Adding PHPTAL

### PR DESCRIPTION
**Pull request by ounziw**
Signed-off-by: Fumito Mizuno mizuno@php-web.net

*Add
packages/parser/classes/view/phptal.php

*Modify
packages/parser/config/parser.php

*Location of PHPTAL library
app/vendor/PHPTAL/
You can change the directory by changing the packages/parser/config/parser.php View_Phptal include.

*Location of cache
app/cache/PHPTAL/
You can change the directory by changing the packages/parser/config/parser.php View_Phptal cache_dir.

PHPTAL is available http://phptal.org/
it is GNU Lesser General Public License.

### CODE REVIEW

**Comment by ounziw** [comment]
I made a mistake on this pull request.

bootstrap.php should be modified also. 
'Parser\View_Phptal' => DIR.'/classes/view/phptal.php', should be added.

which should I do? 
(a) Keep this pull request, and add another pull request (bootstrap.php)
(b) Delete this pull request and make a new pull request (this pull request + bootstrap.php)

**Comment by jschreuder** [comment]
@ounziw apologies for the lack of feedback. This looks good to me except for some weird spacing added in the config file and the `{` being on the same line as the `foreach` statement, those have to be on their own line as per our coding standards.

**Comment by ounziw** [comment]
Dear jschreuder,

Thanks for reply.
I previewed on github.com and I have broken spaces. I'm verry sorry to bother you.

I adjusted spaces and indenting.

**Comment by jschreuder** [comment]
Thanks for the quick reply, now it can be part of 1.2 :)

**Pull request merged**
