### PR TITLE
Fixed parser View::factory() incompatibility with Fuel View:factory()

### PR DESCRIPTION
**Pull request by billmn**
This cause an error in log :

Declaration of Parser\View::factory() should be compatible with that of Fuel\Core\View::factory() in ...packages/parser/classes/view.php on line 17

### CODE REVIEW

**Comment by billmn** [comment]
Core View class __construct() already check if $data is an object or an array and process it ... so I think array declaration in factory() method is not required

**Comment by jschreuder** [comment]
@WanWizard recently someone allowed for objects as well as arrays for data input, I'm not too sure about that but while it's in the core it should be in here as well.

@billmn it seems it's not really necessary to have the exact same init method in each class, just replace `__CLASS__` with `get_called_class()` and ensure that's not the same as `__CLASS__` (thus preventing Parser\View from running it) and you can make this part of the Parser\View class:

```
// Get class name
$class = \Inflector::denamespace(get_called_class());

if ($class !== __CLASS__)
{
    // Include necessary files
    foreach ((array) \Config::get('parser.'.$class.'.include', array()) as $include)
    {
        require_once $include;
    }
}
```

**Note: I edited the code a bit after first submit.**

**Comment by billmn** [comment]
I've changed code to use a general include method for parsers libraries and it works fine ... thank you @jschreuder!

So ... in a \Parser\View::factory() method I've removed "array" in last commit to ( temporary? ) fix the continuous errors written to the logs.

What we have to do to fix it permanently?

**Comment by jschreuder** [comment]
As long as the core works like this the Parser\View class should as well, thus it's not broken and doesn't need fixing.

**Pull request merged**
